"""Package v1.0.0: one stock-style trimmed rarity outline."""
import json
import shutil
import subprocess
import zipfile
from pathlib import Path
import build_rarity as r

ROOT = Path(__file__).resolve().parent
stage = ROOT / 'staging-v100'
dist = ROOT.parent / 'releases/BetterQuickslots-v1.0.0'
containers = ROOT / 'verify-v100-containers'
verified = ROOT / 'verify-v100'
ui = Path('Dawnwalker/Content/_Dawnwalker/UI/_Unified')
for directory in (stage, dist, containers, verified):
    directory.mkdir(exist_ok=True)

# Restore the confirmed original geometry and use an alpha-trimmed private sprite.
from build_trimmed_sprite import build as build_trimmed, ATLAS
trimmed_assets, trimmed_bulk = build_trimmed()
trimmed_package = r.add_import('/Game/_Dawnwalker/UI/_Unified/HUD/Quickslots/Atlas/Frames/T_Quickslot_RarityTrimmed', 0, cn='Package')
trimmed_resource = r.add_import('T_Quickslot_RarityTrimmed', trimmed_package,
                                cp='/Script/Paper2D', cn='PaperSprite')
for name in r.glow_names:
    layer = r.get_exp(r.b, name)
    brush = next(p for p in layer['Data'] if p['Name'] == 'Brush')
    next(p for p in brush['Value'] if p['Name'] == 'ResourceObject')['Value'] = trimmed_resource
    layer['CreateBeforeSerializationDependencies'].append(trimmed_resource)
    # Keep the existing widget tree and update bytecode stable, but render only
    # the innermost (1.19x) outline. Collapsed outer layers cannot add the
    # stepped bevel or darken the retained line when their opacity updates.
    visibility = next(p for p in layer['Data'] if p['Name'] == 'Visibility')
    visibility['Value'] = 'HitTestInvisible' if name == r.glow_names[-1] else 'Collapsed'

r.collect_names(r.b)
(r.BUTTON_DIR / 'rarity-button.json').write_text(json.dumps(r.b, indent=2), encoding='utf-8')

# Reverse only the inventory class rename. All appearance and update bytecode
# are generated by the same builder, including the addressable rarity local.
shared = json.loads(json.dumps(r.b).replace(r.NEW, r.OLD))

# Cooked consumers serialize instances using the stock class property order.
# Appending members to that class shifts inherited property indices in their
# unversioned data. Keep its exact schema; resolve added images through the
# existing ItemBox's parent instead of new widget-binding fields.
original = json.loads((ROOT / 'decoded/button.json').read_text(encoding='utf-8-sig'))
shared_class = r.get_exp(shared, r.OLD + '_C')
shared_class['LoadedProperties'] = r.get_exp(original, r.OLD + '_C')['LoadedProperties']
for name in r.glow_names:
    next(p for p in r.get_exp(shared, name)['Data'] if p['Name'] == 'bIsVariable')['Value'] = False

def lookup(layer):
    parent = r.ctx(r.var('ItemBox', r.owner),
                   r.ex('FinalFunction', StackNode=r.get_parent, Parameters=[]))
    child = r.ctx(parent, r.ex('FinalFunction', StackNode=r.get_child,
                              Parameters=[r.ex('IntConst', Value=layer)]))
    return r.ex('DynamicCast', ClassPtr=r.image_class, Target=child)

def replace_binding(value):
    if isinstance(value, dict):
        if 'EX_InstanceVariable,' in value.get('$type', ''):
            path = value['Variable']['New']['Path']
            if len(path) == 1 and path[0] in r.glow_names:
                return lookup(r.glow_names.index(path[0]))
        result = {k: replace_binding(v) for k, v in value.items()}
        if 'EX_Context,' in result.get('$type', ''):
            result['Offset'] = r.sz(result['ContextExpression'])
        return result
    if isinstance(value, list):
        return [replace_binding(v) for v in value]
    return value

rarity = r.get_exp(shared, 'QSH_UpdateRarity')
rarity['ScriptBytecode'] = replace_binding(rarity['ScriptBytecode'])
rarity['ScriptBytecode'][5]['CodeOffset'] = sum(map(r.sz, rarity['ScriptBytecode'][:-2]))
rarity['ScriptBytecodeSize'] = sum(map(r.sz, rarity['ScriptBytecode']))
assert shared_class['LoadedProperties'] == r.get_exp(original, r.OLD + '_C')['LoadedProperties']
# Verify that the lookup path really reaches the five added images in order.
item_box = r.get_exp(shared, 'ItemBox')
item_slot = shared['Exports'][next(p['Value'] for p in item_box['Data'] if p['Name'] == 'Slot') - 1]
parent = shared['Exports'][next(p['Value'] for p in item_slot['Data'] if p['Name'] == 'Parent') - 1]
slots = next(p['Value'] for p in parent['Data'] if p['Name'] == 'Slots')
for i, name in enumerate(r.glow_names):
    slot = shared['Exports'][slots[i]['Value'] - 1]
    child = shared['Exports'][next(p['Value'] for p in slot['Data'] if p['Name'] == 'Content') - 1]
    assert child['ObjectName'] == name
r.collect_names(shared)
shared_source = r.BUTTON_DIR / 'rarity-shared-button.json'
shared_source.write_text(json.dumps(shared, indent=2), encoding='utf-8')
assets = [
    (r.BUTTON_DIR / 'rarity-button.json', ui / 'HUD/Quickslots/WBP_Inventory_QuickslotRarity.uasset'),
    (r.INV_DIR / 'rarity-quickslots.json', ui / 'GameHub/Inventory/WBP_Inventory_Quickslots_QSH.uasset'),
    (r.INV_DIR / 'rarity-hub.json', ui / 'GameHub/Inventory/WBP_Hub_NewInventory.uasset'),
    (shared_source, ui / 'HUD/Quickslots/WBP_HUD_Quickslots_Button.uasset'),
]

def run(*args):
    subprocess.run([str(a) for a in args], cwd=ROOT, check=True,
                   creationflags=subprocess.CREATE_NO_WINDOW)

gui = ROOT / 'tools/UAssetGUI.exe'
retoc = ROOT / 'tools/retoc/retoc.exe'
for source, relative in assets:
    target = stage / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    run(gui, 'fromjson', source, target, 'Dawnwalker')
    assert target.exists() and target.with_suffix('.uexp').exists()

for source, relative in trimmed_assets:
    target = stage / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    run(gui, 'fromjson', source, target, 'Dawnwalker')
shutil.copy2(trimmed_bulk, stage / ATLAS.with_suffix('.ubulk'))
assets.extend(trimmed_assets)

stem = '00000000_BetterQuickslots_P'
run(retoc, 'to-zen', stage, dist / (stem + '.utoc'), '--version', 'UE5_5')
run(retoc, 'verify', dist / (stem + '.utoc'))
for name in ('global.utoc', 'global.ucas', 'references.utoc', 'references.ucas', 'references.pak'):
    shutil.copy2(ROOT / 'verify-v02-containers' / name, containers / name)
for suffix in ('.utoc', '.ucas'):
    shutil.copy2(dist / (stem + suffix), containers / (stem + suffix))
run(retoc, 'to-legacy', containers, verified, '--version', 'UE5_5', '--no-shaders')
for source, relative in assets:
    output = verified / (relative.stem + '.json')
    run(gui, 'tojson', verified / relative, output, 'VER_UE5_5', 'Dawnwalker')

# Compare the packaged functions, imports, and authored widget properties.
def properties(value):
    if isinstance(value, dict):
        return {k: properties(v) for k, v in value.items() if k != 'IsZero'}
    if isinstance(value, list):
        result = [properties(v) for v in value]
        if result and all(isinstance(v, dict) and 'Name' in v for v in result):
            result.sort(key=lambda v: v['Name'])
        return result
    if value in ('+0', '-0'):
        return 0.0
    return round(value, 6) if isinstance(value, float) else value

for source, relative in assets:
    expected = json.loads(source.read_text(encoding='utf-8-sig'))
    actual = json.loads((verified / (relative.stem + '.json')).read_text(encoding='utf-8-sig'))
    for a, b in zip(expected['Imports'], actual['Imports']):
        # The local reference set lacks Paper2D's default sprite material.
        # Retoc cannot recover those two names; they are copied unchanged
        # from the stock sprite and are resolved from the game at runtime.
        if relative == trimmed_assets[1][1] and a['ObjectName'] in (
            'TranslucentUnlitSpriteMaterial', '/Paper2D/TranslucentUnlitSpriteMaterial'
        ):
            assert b['ObjectName'] in (a['ObjectName'], 'UnknownExport', '/Engine/UnknownPackage')
            assert a['OuterIndex'] == b['OuterIndex']
        else:
            assert a == b, (relative, a, b)
    assert len(expected['Imports']) == len(actual['Imports'])
    assert len(expected['Exports']) == len(actual['Exports']), relative
    for a, b in zip(expected['Exports'], actual['Exports']):
        assert a['ObjectName'] == b['ObjectName']
        for key in ('ScriptBytecode', 'ScriptBytecodeSize', 'LoadedProperties', 'Data'):
            if key in a:
                assert properties(a[key]) == properties(b[key]), (relative, a['ObjectName'], key)
    if relative == ATLAS:
        assert expected['Exports'][0]['Extras'] == actual['Exports'][0]['Extras'], 'Inline texture mips changed'
assert len(list(stage.rglob('*.uasset'))) == 6
assert (verified / ATLAS.with_suffix('.ubulk')).read_bytes() == trimmed_bulk.read_bytes()
# Stock consumer templates must decode identically with the patched shared
# class as their dependency. This catches inherited-property schema shifts
# that comparing only our newly packaged assets cannot detect.
for relative, stock_json in (
    (ui / 'HUD/Quickslots/WBP_HUD_Quickslots.uasset', 'gameplay-quickslots.json'),
    (ui / 'GameHub/Inventory/WBP_Inventory_Quickslots.uasset', 'quickslots.json'),
):
    target = verified / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    for suffix in ('.uasset', '.uexp'):
        shutil.copy2(ROOT / 'extracted' / relative.with_suffix(suffix), target.with_suffix(suffix))
    output = verified / ('consumer-' + stock_json)
    run(gui, 'tojson', target, output, 'VER_UE5_5', 'Dawnwalker')
    stock = json.loads((ROOT / 'decoded' / stock_json).read_text(encoding='utf-8-sig'))
    recovered = json.loads(output.read_text(encoding='utf-8-sig'))
    assert len(stock['Exports']) == len(recovered['Exports'])
    for a, b in zip(stock['Exports'], recovered['Exports']):
        assert a['ObjectName'] == b['ObjectName']
        if 'Data' in a:
            assert properties(a['Data']) == properties(b['Data']), (relative, a['ObjectName'], 'stock consumer schema')
print('PASS: stock HUD and crafting quickslot templates decode unchanged against the patched class.')
# The layout and hover screen remain byte-identical; only button visuals change.
for _, relative in assets[1:3]:
    for suffix in ('.uasset', '.uexp'):
        assert (stage / relative.with_suffix(suffix)).read_bytes() == (ROOT / 'staging-v02' / relative.with_suffix(suffix)).read_bytes(), relative
for _, relative in (assets[0], assets[3]):
    actual = json.loads((verified / (relative.stem + '.json')).read_text(encoding='utf-8-sig'))
    previous = json.loads((ROOT / 'verify-v041' / (relative.stem + '.json')).read_text(encoding='utf-8-sig'))
    for a, b in zip(actual['Exports'], previous['Exports']):
        for key in ('ScriptBytecode', 'ScriptBytecodeSize', 'LoadedProperties'):
            if key in a:
                assert properties(a[key]) == properties(b[key]), (relative, a['ObjectName'], key)
    for name in ('Background', 'ItemIcon', 'ItemBox', 'StackSize'):
        assert r.get_exp(actual, name)['Data'] == r.get_exp(previous, name)['Data']
    visible = [r.get_exp(actual, name) for name in r.glow_names
               if next(p['Value'] for p in r.get_exp(actual, name)['Data'] if p['Name'] == 'Visibility') != 'Collapsed']
    assert len(visible) == 1 and visible[0]['ObjectName'] == r.glow_names[-1]
    transform = next(p for p in visible[0]['Data'] if p['Name'] == 'RenderTransform')
    scale = next(p['Value'][0]['Value'] for p in transform['Value'] if p['Name'] == 'Scale')
    assert properties(scale['X']) == 1.19 and properties(scale['Y']) == 1.19
print('PASS: one visible stock-artwork rarity outline; original bytecode, schemas, backgrounds, icons and counts preserved.')

readme = '''Better Quickslots — v1.0.0

First stable release. The three installed mod files are byte-for-byte identical
to the confirmed v0.4.4 build. This release changes version labels and documentation,
with no gameplay or visual changes. Existing v0.4.4 users do not need to reinstall.

FEATURES
Thin, stock-style item rarity borders for inventory, crafting, and gameplay
quickslots, plus inventory quickslot hover details. Preserves the original
artwork, icons, counts and layout. Borders update when displayed items change;
empty slots have no rarity outline. UE4SS is not required.

INSTALL / UPGRADE
Close the game. Extract this ZIP and copy all three files together into:
<game installation folder>\\Dawnwalker\\Content\\Paks\\~mods

00000000_BetterQuickslots_P.pak
00000000_BetterQuickslots_P.ucas
00000000_BetterQuickslots_P.utoc

Create ~mods if needed. Replace all three Better Quickslots files together.
If upgrading from the former Quickslot Hover mod, remove its three old mod
files first or disable that version in your mod manager. These filenames will
not overwrite the old names. Never keep both versions installed.

UNINSTALL
Close the game and remove only the three Better Quickslots files listed above.
UE4SS and other mods can stay installed.

COMPATIBILITY
Other mods replacing WBP_Hub_NewInventory or WBP_HUD_Quickslots_Button may conflict.
Game updates may require rebuilding. The same button is used by inventory,
crafting and gameplay. Do not assume compatibility with every future game patch.

VALIDATION / SOURCE
Based on v0.4.4, confirmed working and visually approved in game. Package integrity,
recovered Blueprint assets, texture mip bytes and stock consumer compatibility
were verified for that build. v1.0.0 preserves the three mod files exactly.

Source, build instructions and release history:
https://github.com/t0ddharris/Better-Quickslots
'''

(dist / 'README.txt').write_text(readme, encoding='utf-8')
archive = ROOT.parent / 'releases/BetterQuickslots-v1.0.0.zip'
with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED) as z:
    for name in ('README.txt', *(stem + suffix for suffix in ('.pak', '.ucas', '.utoc'))):
        z.write(dist / name, name)
print(f'Release: {archive}')
